

# This workflow will test a Python project

name: Unit tests with Python

on:
  push:
    branches: [main]
    paths:
      - 'example-python/**'
  pull_request:
    branches: [main]
    paths:
      - 'example-python/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # step 1 - clone project
    - name: Checkout the repository
      uses: actions/checkout@v4

    # step 2 - provide python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # step 3 - run tests
    - name: Test with Python
      run: |
        cd example-python
        python3 -m unittest tests.test_town.TestTown

